const errors = {
    GENERAL_ERROR: 'Der opstod en fejl. Pr√∏v igen.',
};

export default errors;
